### ISSUE TITLE
Hamtaro Rainbow Rescue freeze on Spanish language 

### ISSUE THREAD

**Issue by benderscruffy** [fleroviux/NanoboyAdvance#91]
On new game in Hamtaro Rainbow Rescue freezes on Spanish language selection any other language works fine

**Comment by endrift** [comment]
mGBA had this bug too: https://github.com/mgba-emu/mgba/issues/1098. I do not know which commit fixed it offhand.

**Comment by fleroviux** [comment]
Huh I was pretty sure I rechecked this game, after fixing #109 but apparently I didn't!
Apparently this was fixed in https://github.com/fleroviux/NanoboyAdvance/commit/066dc387b9636e2e72bc72afc8cd999f72299d63 as well. Weirdly enough the Hello Kitty game now also seems to work fine, I didn't even make an attempt to handle sub-instruction DMA open bus.

**Comment by endrift** [comment]
To me that says your DMAs aren't blocking the CPU, which is incorrect behavior according to GBATEK.

**Comment by fleroviux** [comment]
My DMAs should be blocking the CPU. 

I guess this might just work out because my open bus read handler returns whatever the DMA previously read when a DMA is active and a prefetched opcode otherwise. 

But since the condition for DMA may become true sub-instruction when setting up an immediate DMA, it may just return whatever the DMA read the previous time it ran and that might just be messed up enough to """work""".

I am currently attempting to properly emulate the open bus (including leaking data leaks etc) and I guess if it breaks after that I'll have to deal with this properly. But that needs for research, since open bus appears to be even messier than I thought it was.
